version: 2
jobs:
  build:
    working_directory: /go/src/github.com/avhimkov/MFC_LogWork
    docker:
      - image: circleci/golang:1.12.0
    environment:
      IMPORT_PATH: "github.com/avhimkov/MFC_LogWork"
      - GOCACHE: "/tmp/go/cache"
      - DEP_VERSION: 0.5.0
    steps:
      - run: git config --global url.ssh://git@github.com/avhimkov.insteadOf https://github.com/avhimkov
      - checkout

dependencies:
  pre:
    - go get github.com/tools/godep

  override:
    - mkdir -p "$GOPATH/src/$IMPORT_PATH"
    - rsync -azC --delete ./ "$GOPATH/src/$IMPORT_PATH/"

test:
  pre:
    - go vet ./...

  override:
    - godep go test ./...